server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: garage-simulator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/garage_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
simulator:
  base-url: http://localhost:3003