server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: garage-simulator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/garage_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
simulator:
  base-url: http://localhost:3003
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.zalando.logbook: DEBUG

logbook:
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - Cookie

garage:
  event:
    url: ${GARAGE_EVENT_URL:http://localhost:3000}